services:
  app:
    build:
      context: .
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        INTERNAL_API_URL: ${INTERNAL_API_URL}
        SITE_URL: ${SITE_URL}
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    container_name: stockdemy-app
    restart: unless-stopped
    env_file:
      - .env
    expose:
      - "3000"

  nginx:
    image: nginx:1.27-alpine
    container_name: stockdemy-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app